name: optimized_cached_image
description: A library for loading images from network, resizing as per container size and caching while being memory sensitive.
version: 2.0.0-dev.1
homepage: https://github.com/humblerookie/optimized_cached_image

environment:
  sdk: ">=2.6.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^2.1.0
  flutter_image_compress: ^0.7.0
  uuid: ^2.0.4
  http: ^0.13.0
  path_provider: ^1.6.18
  path: ^1.8.0
  pedantic: ^1.8.0+1
  sprintf: ^4.0.0
  octo_image: 1.0.0-nullsafety.1
  image: ^3.0.1
dev_dependencies:
  test: 1.9.4
